### ISSUE TITLE
Installation issue with Apple M1 "flame": plugin "flame" does not offer installation for this platform

### ISSUE THREAD

**Issue by Adiii717** [yahoo/kubectl-flame#61]
Getting below error when tried to install on Apple M1. 
```
kubectl krew install  flame

Updated the local copy of plugin index.
Installing plugin: flame
W0811 10:26:30.223383   21587 install.go:164] failed to install plugin "flame": plugin "flame" does not offer installation for this platform
F0811 10:26:30.223437   21587 root.go:79] failed to install some plugins: [flame]: plugin "flame" does not offer installation for this platform
```

**Comment by edeNFed** [comment]
closed by #56

**Comment by ramnes** [comment]
#56 matches Linux, not Darwin – the issue remains. :)

**Comment by williamchong** [comment]
Same issue, please  reopen

**Comment by sid-maddy** [comment]
@edeNFed, #56 does not resolve this issue as mentioned [above](https://github.com/yahoo/kubectl-flame/issues/61#issuecomment-1046895651).

**Comment by lavelle96** [comment]
I have the same issue, have re raised here for visibility: https://github.com/yahoo/kubectl-flame/issues/74

**Comment by insdami** [comment]
Same issue
```
Updated the local copy of plugin index.
Installing plugin: flame
W0821 10:30:04.442884   61694 install.go:164] failed to install plugin "flame": plugin "flame" does not offer installation for this platform
failed to install some plugins: [flame]: plugin "flame" does not offer installation for this platform
```

**Comment by gokalper** [comment]
Same issue

```Installing plugin: flame
W0509 08:05:00.232364   26345 install.go:164] failed to install plugin "flame": plugin "flame" does not offer installation for this platform
failed to install some plugins: [flame]: plugin "flame" does not offer installation for this platform```

**Comment by gokalper** [comment]
you can build and install manually on apple silicon :

```
# CLONE THE REPO

export PLUGIN_VERSION=v0.2.4
export PLUGIN_COMMIT=dede84c3ad0857ce5a53be8aeb09ae70b253fcfa
export PLUGIN_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")

CGO_ENABLED=0 GOOS=darwin go build -ldflags "-X github.com/VerizonMedia/kubectl-flame/cli/cmd/version.semver=$PLUGIN_VERSION -X github.com/VerizonMedia/kubectl-flame/cli/cmd/version.date=$PLUGIN_DATE -X github.com/VerizonMedia/kubectl-flame/cli/cmd/version.commit=$PLUGIN_COMMIT" -o kubectl-flame ./cli/main.go



zip kubectl-flame.zip kubectl-flame LICENSE
export PLUGIN_SHA=$(shasum -a 256 kubectl-flame.zip | awk '{print $1}')

cat <<EOF > manifest.yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: flame
spec:
  version: $PLUGIN_VERSION
  homepage: https://github.com/VerizonMedia/kubectl-flame
  shortDescription: A Kubernetes plugin for flame graph generation.
  platforms:
    - uri: https://localhost:8000/kubectl-flame.zip
      sha256: $PLUGIN_SHA
      bin: kubectl-flame
      files:
        - from: kubectl-flame
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: darwin
          arch: arm64
EOF

# IN THE ROOT FOLDER RUN
python3 -m http.server

# IN A NEW TERMINAL AT THE ROOL FOLDER RUN
kubectl krew install --manifest=manifest.yaml --archive=kubectl-flame.zip
```
